#export COMPANY=$1
python3 twitter-scrapper.py "\$AMZN"
python3 twitter-scrapper.py "\$EBAY"
python3 twitter-scrapper.py "\$ADBE"
python3 twitter-scrapper.py "\$GOOG"
python3 twitter-scrapper.py "\$FB"
python3 twitter-scrapper.py "\$AAPL"
python3 twitter-scrapper.py "\$JPM"
python3 twitter-scrapper.py "\$WMT"
python3 twitter-scrapper.py "\$MCD"
python3 twitter-scrapper.py "\$KO"
python3 twitter-scrapper.py "\$GE"
python3 twitter-scrapper.py "\$GM"
python3 twitter-scrapper.py "\$GS"
python3 twitter-scrapper.py "\$F"
python3 twitter-scrapper.py "\$SLB"
python3 twitter-scrapper.py "\$NKE"
python3 twitter-scrapper.py "\$PG"
python3 twitter-scrapper.py "\$HPQ"
python3 twitter-scrapper.py "\$PFE"
python3 twitter-scrapper.py "\$MA"
#python3 twitter-scrapper.py

echo "Done Moj Lo ...!"