#export COMPANY=$1
#python3 twitter-scrapper.py "\$AMZN"
#python3 twitter-scrapper.py "\$EBAY"
#python3 twitter-scrapper.py "\$ADBE"
#python3 twitter-scrapper.py "\$GOOG"
#python3 twitter-scrapper.py "\$FB"
#python3 twitter-scrapper.py "\$AAPL"
#python3 twitter-scrapper.py "\$JPM"
#python3 twitter-scrapper.py "\$WMT"
#python3 twitter-scrapper.py "\$MCD"
#python3 twitter-scrapper.py "\$KO"
#python3 twitter-scrapper.py "\$GE"
#python3 twitter-scrapper.py "\$GM"
#python3 twitter-scrapper.py "\$GS"
#python3 twitter-scrapper.py "\$F"
#python3 twitter-scrapper.py "\$SLB"
#python3 twitter-scrapper.py "\$NKE"
#python3 twitter-scrapper.py "\$PG"
#python3 twitter-scrapper.py "\$HPQ"
#python3 twitter-scrapper.py "\$PFE"
#python3 twitter-scrapper.py "\$MA"
#python3 twitter-scrapper.py


python3 sentiment.py "\$AMZN"
python3 sentiment.py "\$EBAY"
python3 sentiment.py "\$ADBE"
python3 sentiment.py "\$GOOG"
python3 sentiment.py "\$FB"
python3 sentiment.py "\$AAPL"
python3 sentiment.py "\$JPM"
python3 sentiment.py "\$WMT"
python3 sentiment.py "\$MCD"
python3 sentiment.py "\$KO"
python3 sentiment.py "\$GE"
python3 sentiment.py "\$GM"
python3 sentiment.py "\$GS"
python3 sentiment.py "\$F"
python3 sentiment.py "\$SLB"
python3 sentiment.py "\$NKE"
python3 sentiment.py "\$PG"
python3 sentiment.py "\$HPQ"
python3 sentiment.py "\$PFE"
python3 sentiment.py "\$MA"

echo "Done Moj Lo ...!"